[feat/activate_trash_icon]: 5분 이상 사용 앱 삭제 불가 기능 추가
Team-HMH/HMH-Android pull request #176
Opened 2024-04-02 11:32 UTC by jihyun0v0

## 개요
- close #174 

## 작업 사항
- 5분 미만 사용 여부를 리사이클러뷰 뷰홀더에서 참조할 수 있도록 데이터 클래스 구조/클래스 명 변경
- 리사이클러뷰 뷰홀더에서 해당 멤버 변수를 참조하여 쓰레기통 아이콘 set
- 5분 이상 사용한 앱에 대해 삭제 시도시 토스트 메세지 추가
- challengeFragment 리팩토링

## 스크린샷(optional)
![image](https://github.com/Team-HMH/HMH-Android/assets/84266681/83bc79eb-43ab-47b1-be68-e48dd360745c)
<img width="245" alt="image" src="https://github.com/Team-HMH/HMH-Android/assets/84266681/01b10bd6-8b20-47a5-bfe0-0c751ec31d17">

2024-04-11 09:27 UTC, KwakEuiJin approved these changes
이거 좀만 더 보는 중 전체적으로 함수명 변수명 잘 바꾸었네요 다만 첨보는 함수들이?!

2024-04-11 09:27 UTC, KwakEuiJin commented on core/viewmodel/main/src/main/java/com/hmh/hamyeonham/core/viewmodel/MainViewModel.kt
> +                //setUsageGaols(it)
주석은 뭐에욤?!

2024-04-11 09:27 UTC, KwakEuiJin commented on feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
> +            initChallengeState(it)
collectMainState 요런 함수가 있었나?!

2024-04-11 09:27 UTC, KwakEuiJin commented on feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
> +    }
업데이트는 뷰모델에서만~!!

2024-04-11 09:27 UTC, KwakEuiJin requested changes
어프로브는 실수

2024-04-15 08:04 UTC, jihyun0v0 commented on feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
> +            initChallengeState(it)
제가 함수로 정리해서 만든 건데... 수정할까요?

2024-04-15 08:46 UTC, jihyun0v0 commented on feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
> +    }
흐음 그러면 fragment에서 받은 정보를 viewModel에 어떻게 전달하면 될까요??  124, 130번줄 코드의 다른 update들도 이런 식이어서 어떻게 해야할지 감이 안오네욤,,!

2024-04-15 09:36 UTC, jihyun0v0 commented on feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
> +    }
제가 이해한 선에서 viewModel로 update하는 로직을 옮겼는데 한번 확인 부탁합니당~~

2024-04-28 13:20 UTC, KwakEuiJin commented on feature/challenge/src/main/java/com/hmh/hamyeonham/challenge/ChallengeFragment.kt
> +            initChallengeState(it)
옙 수정 필요할 것 같아요, ViewModel로 viewLifeCycle을 던져서 구독하는 방식이 관심사 분리 측면에서 옳지 않은 것 같아요, 이런 구조의 경우 전부 원래대로 원복 부탁드립니다

2024-05-15 13:39 UTC, KwakEuiJin approved these changes

2024-05-15 13:40 UTC, merged