[Feat/usagestatusmanager] : 이용시간 통계 뷰 구현
Team-HMH/HMH-Android pull request #33
Opened 2024-01-03 07:43 UTC by memoryBangwool

## 개요
- close #27 

## 작업 사항
- 이용시간 통계 query 구현
- 이용시간 통계 프로그래스바로 나타내기
- 이용시간 통계 뷰 ui 구현

## 변경 사항(optional)
- 기존에 의진이가 구현했던 DefaultUsageStatsRepository의 getUsageTimeForPackages() 메소드 UsageGoal과의 호환성 때문에 로직 변경 (기능은 같음) 

## 스크린샷(optional)
![Screenshot_20240103-162038](https://github.com/Team-HMH/HMH-Android/assets/84266681/fb46c3d0-4027-48eb-be95-5e1ffecfb7fe)

## 기타
- 텍스트 디자인 등 세부 디자인은 뷰 확정시 수정필요
- 서버 api배포되면 목표 이용시간(UsageGoal)서버통신 이용해 수정 필요

2024-01-03 09:44 UTC, kangyuri1114 reviewed
클릭 아키텍처 열심히 공부한 게 느껴지네요,, 저도 빨리 리팩토링 하겠습니다. 수고하셨어요!

2024-01-03 09:44 UTC, kangyuri1114 commented on core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
> +    Log.d("min", min.toString())
로그가 확인용이라면 확인 후에 push할 때에는 지워줘도 될 것 같습니다!

2024-01-03 09:44 UTC, kangyuri1114 commented on data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
> +            UsageGoalModel("com.android.chrome", 39445),
저 그냥 궁금해서 그런데 이거는 아직 특정 앱 선택 기능이 없어서 임시적으로 더미데이터로 앱 패키지 값을 넣어주신 것 맞을까요??

2024-01-03 09:44 UTC, kangyuri1114 commented on data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
> +            UsageGoalModel("com.android.chrome", 39445),
해당 listOf를 변수로 만들고 변수를 return 하는 것으로 수정하면 가독성이 더 좋아질 것 같습니다.

2024-01-03 09:44 UTC, kangyuri1114 commented on feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsViewModel.kt
> +//            }
이부분도 지워주세요!

2024-01-03 09:44 UTC, kangyuri1114 commented on feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/UsageStaticsViewHolder.kt
> +    }
binidng.~~
을 여러번 쓰는 부분에서는 스코프 함수로
binding.run { ... } 으로 묶어줄 수 있어요!! 가독성을 위해 수정 부탁드립니답

2024-01-03 09:47 UTC, memoryBangwool commented on core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
> +    Log.d("min", min.toString())
넵! 아직 수정할 부분이 남아있을 것 같아 남겨두었습니다! 나중에 로직 완성하면 지우겠습니다~

2024-01-03 09:48 UTC, memoryBangwool commented on data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
> +            UsageGoalModel("com.android.chrome", 39445),
네 맞습니다! 서버에서 받아와야 하는 정보인데 일단 급하게 만든 거여서 가독성도 아주,,, bad
수정하겠습니다.

2024-01-03 09:48 UTC, memoryBangwool commented on feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/StaticsViewModel.kt
> +//            }
헉스 넴,,,

2024-01-03 09:48 UTC, memoryBangwool commented on feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/UsageStaticsViewHolder.kt
> +    }
네 감사합니다!

2024-01-03 18:25 UTC, jumining reviewed
짱빠르다 안드..놀랍다..

2024-01-04 00:25 UTC, KwakEuiJin commented
> 짱빠르다 안드..놀랍다..

ㅋㅋㅋㅋㅋㅋ 대장님 반갑습니당

2024-01-04 00:35 UTC, KwakEuiJin requested changes
코멘트 확인하고 리마인드 부탁드려요~!!
특히 도메인 코드 너무 좋았습니당

2024-01-04 00:35 UTC, KwakEuiJin commented on core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
> +    Log.d("min", min.toString())
이거 이제 지우기 ㄱㄱ?!

2024-01-04 00:35 UTC, KwakEuiJin commented on core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
> +}
이 함수들이 해당 파일에 있는 것이 맞을까요?? 관심사가 조금 다른 것 같습니다.

2024-01-04 00:35 UTC, KwakEuiJin commented on data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
> +    }
음 이렇게 주입해줄거면 차라리 데이터 소스쪽에서 get하는 함수내에서 선언해주는 것이 더 좋을 것 같습니다, 그냥 싱글톤구조에 list넣어둔 것과 다른게 없어보여요!

2024-01-04 00:35 UTC, KwakEuiJin commented on domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/StaticsUseCase.kt
> +        private fun getTotalUsage(
도메인 로직이 좀 장난 아닌데요? 이런 구조를 생각하시고 개발하신 우리 팀원 너무 든든합니다 👍

2024-01-04 00:35 UTC, KwakEuiJin commented on feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/UsageStaticsTotalViewHolder.kt
> +    fun onBind(usageStatAndGoal: UsageStatAndGoal) {
줄바꿈 무언가 이상합니다?!?! 혹시 셋팅이...!!??

2024-01-04 01:37 UTC, memoryBangwool commented on core/common/src/main/java/com/hmh/hamyeonham/common/time/TimeExt.kt
> +}
네! 어제 스크럼 이후에 수정하려 했는데 아직 못했네요. 오늘 스크럼 전까지 해서 올리겠습니다!

2024-01-04 01:37 UTC, memoryBangwool commented on data/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/di/UsageGoalsModule.kt
> +    }
넵 수정하겠습니다!

2024-01-04 01:37 UTC, memoryBangwool commented on feature/statistics/src/main/java/com/hmh/hamyeonham/statistics/UsageStaticsTotalViewHolder.kt
> +    fun onBind(usageStatAndGoal: UsageStatAndGoal) {
허거덩 확인해보겠습니다

2024-01-04 01:38 UTC, memoryBangwool commented on domain/usagestats/src/main/java/com/hmh/hamyeonham/usagestats/usecase/StaticsUseCase.kt
> +        private fun getTotalUsage(
의진 스승님 코드 따라해보았읍니다. 더 가르쳐주십시오 꾸벅

2024-01-04 06:42 UTC, l2hyunwoo commented
> 짱빠르다 안드..놀랍다..

@jumining 우리 의진이 잘 부탁한다

2024-01-04 12:34 UTC, KwakEuiJin commented
컨플릿 제가 해결할게요

2024-01-04 14:23 UTC, KwakEuiJin approved these changes
고생하셨어요~!!

2024-01-04 14:23 UTC, merged